backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "works"
    label: "Works"
    label_singular: "Work"
    folder: "src/content/works"
    create: true
    format: json-frontmatter
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number", default: 2025}
      - {label: "Description", name: "description", widget: "text", required: false}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - name: "me"
        label: "About (Me)"
        file: "src/content/pages/me.md"
        fields:
          - {label: "Heading", name: "title", widget: "string"}
          - {label: "Photo", name: "photo", widget: "image", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Bio", name: "body", widget: "markdown"}
